# Generated by Django 5.1 on 2024-08-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
    ]
