# Generated by Django 5.1 on 2024-08-20 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app_management.app'),
        ),
    ]
