# Generated by Django 5.1 on 2024-08-23 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0003_alter_payment_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('parameters', models.CharField(blank=True, max_length=512)),
                ('return_type', models.CharField(blank=True, max_length=255)),
                ('app_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.app')),
            ],
        ),
    ]
