# Generated by Django 5.1 on 2024-08-28 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0005_function_created_at_function_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='function',
            name='return_type',
        ),
    ]
