# Generated by Django 5.1 on 2024-08-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0006_remove_function_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
