# Generated by Django 5.1 on 2024-08-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0007_function_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('app_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.app')),
                ('function_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_management.function')),
            ],
        ),
    ]
