# Generated by Django 5.1 on 2024-08-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0008_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='packages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
