# Generated by Django 5.1 on 2024-09-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0009_function_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionversion',
            name='packages',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
