# Generated by Django 5.1 on 2024-09-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0010_functionversion_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
