# Generated by Django 5.1 on 2024-09-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0011_alter_function_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='python',
            field=models.TextField(blank=True, null=True),
        ),
    ]
