# Generated by Django 5.1 on 2024-09-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0012_function_python'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='code',
        ),
    ]
