# Generated by Django 5.1 on 2024-09-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0014_rename_python_function_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='code',
            new_name='python_code',
        ),
    ]
