# Generated by Django 5.1 on 2024-09-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0015_rename_code_function_python_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='python_code',
            new_name='python',
        ),
    ]
