# Generated by Django 5.1 on 2024-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0016_rename_python_code_function_python'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
