# Generated by Django 5.1 on 2024-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='website',
            name='tags',
            field=models.ManyToManyField(related_name='websites', to='dreamspace.tag'),
        ),
        migrations.AddField(
            model_name='websiteversion',
            name='tags',
            field=models.ManyToManyField(related_name='website_versions', to='dreamspace.tag'),
        ),
    ]
