# Generated by Django 5.1 on 2024-09-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0002_tag_alter_website_is_active_website_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=255)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('website_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamspace.website')),
            ],
        ),
    ]
