# Generated by Django 5.1 on 2024-09-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0003_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteversion',
            name='tags',
            field=models.ManyToManyField(to='dreamspace.tag'),
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.ManyToManyField(to='dreamspace.tag')),
                ('websites', models.ManyToManyField(blank=True, related_name='apps', to='dreamspace.website')),
            ],
        ),
    ]
