# Generated by Django 5.1 on 2024-09-12 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0005_rename_websites_app_website_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='App_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamspace.app'),
        ),
    ]
