# Generated by Django 5.1 on 2024-09-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0006_log_app_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='App_relation',
            new_name='app_relation',
        ),
    ]
