# Generated by Django 5.1 on 2024-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0007_rename_app_relation_log_app_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
