# Generated by Django 5.1 on 2024-09-13 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0008_app_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('packages', models.TextField(blank=True, null=True)),
                ('python', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamspace.app')),
                ('tags', models.ManyToManyField(to='dreamspace.tag')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='function_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dreamspace.function'),
        ),
        migrations.CreateModel(
            name='FunctionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('packages', models.TextField()),
                ('python', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dreamspace.function')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('function', 'version')},
            },
        ),
    ]
