# Generated by Django 5.1 on 2024-09-16 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0010_function_is_active_function_is_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('packages', models.TextField(blank=True, null=True)),
                ('python', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamspace.app')),
            ],
        ),
    ]
