# Generated by Django 5.1 on 2024-09-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0011_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='functionversion',
            name='packages',
        ),
        migrations.RemoveField(
            model_name='models',
            name='packages',
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.TextField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, null=True)),
                ('function_relation', models.ManyToManyField(blank=True, related_name='packages', to='dreamspace.function')),
                ('modeles_relation', models.ManyToManyField(blank=True, related_name='packages', to='dreamspace.models')),
            ],
        ),
    ]
