# Generated by Django 5.1 on 2024-09-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0012_remove_function_packages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='cmd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
