# Generated by Django 5.1 on 2024-09-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0013_packages_cmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='installation',
            new_name='version',
        ),
    ]
