# Generated by Django 5.1 on 2024-09-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamspace', '0014_rename_installation_packages_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='modeles_relation',
            field=models.ManyToManyField(blank=True, related_name='function', to='dreamspace.models'),
        ),
    ]
